<a href="https://colab.research.google.com/github/rishwanth123115/ML_23AG1A66H8/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
list1 = [3, 5, 7, 9]
array1 = np.array(list1)
print(array1)

[3 5 7 9]


In [3]:
array = np.array([3,5,7,9])
print(array1)

[3 5 7 9]


In [5]:
array1 = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])

print(array1)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
array1 = np.array([[9,8,7,6],
                   [5,4,3,2]])
print(array1)

[[9 8 7 6]
 [5 4 3 2]]


In [7]:
array1 = np.array([[1,2,3,4],
                   [5,6,7,8,],
                   [9,5,2,7]])
print(array1)

[[1 2 3 4]
 [5 6 7 8]
 [9 5 2 7]]


In [8]:
array1 = np.array([[6,8,7,6],
                   [2,5,8,3],
                   [7,5,3,1]])
print(array1)

[[6 8 7 6]
 [2 5 8 3]
 [7 5 3 1]]


In [10]:
array1 = np.array([3, 5, 7])
print(array1.dtype)

int64


In [11]:
print(array1.ndim)

1


In [12]:
print(array1.size)

3


In [13]:
array1 = np.array([[1, 2, 3],
                [6, 7, 8]])
print(array1.shape)

(2, 3)
